version: "3.8"

services:
  react:
    build:
      context: ./LAP-react
      dockerfile: Dockerfile
    container_name: leave-app-frontend-docker
    ports:
      - "3000:3000"
    depends_on:
      - springboot-app

  springboot-app:
    build:
      context: ./LAP-springboot/LeaveApplicationPortal
      dockerfile: Dockerfile
    container_name: leave-app-backend-docker
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: lap
      SPRING_DATA_MONGODB_USERNAME: Vandana
      SPRING_DATA_MONGODB_PASSWORD: Vandu@123
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network
  

networks:
  my-network:
    driver: bridge
