FROM node:20
COPY package*.json ./
RUN npm install -g npm@latest
RUN npm cache clean --force

COPY . .
COPY ./src/images ./src/images
RUN npm run build
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]